---
title: "Heatmaps"
date: "`r Sys.Date()-1`"
output: 
  html_document:
    fig_width: 7.5
---

<BR>
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=F, message=F)
library(ggfortify)
library(ggthemes)
library(lubridate)
library(bbplot)
library(dplyr)
library(markdown)
library(ggrepel)
library(tidyr)
library(tidyverse)
library(plyr)
library(extrafont)
library(showtext)



df <- read.csv("Z:/Scripts/Statistics/todays_data.csv")
df$`SgeneCt` <- replace(df$`SgeneCt`, df$`SgeneCt`==-1, 50)
df$`NgeneCt` <- replace(df$`NgeneCt`, df$`NgeneCt`==-1, 50)
df$`Orf1abCt` <- replace(df$`Orf1abCt`, df$`Orf1abCt`==-1, 50)
df$`Ms2Ct` <- replace(df$`Ms2Ct`, df$`Ms2Ct`==-1, 50)


inc <- subset(df, (Orf1abCt <= 37 & SgeneCt >37 & NgeneCt > 37) | 
                         (Orf1abCt > 37 & SgeneCt <=37 & NgeneCt > 37) | 
                         (Orf1abCt> 37 & SgeneCt >37 & NgeneCt <= 37))

pos <- subset(df, (Orf1abCt <= 37 & SgeneCt <=37) | 
                         (Orf1abCt <= 37 & NgeneCt <= 37) | 
                         (SgeneCt <= 37 & NgeneCt <= 37))
inc <- subset(inc, DateAmplitudeCompleted == Sys.Date()-1)
pos <- subset(pos, DateAmplitudeCompleted == Sys.Date()-1)
empty_plate_map <- function(){
  wells <-c("A01","A02","A03","A04","A05","A06","A07","A08","A09","A10","A11","A12","B01","B02","B03","B04","B05","B06","B07","B08","B09","B10","B11","B12","C01","C02","C03","C04","C05","C06","C07","C08","C09","C10","C11","C12","D01","D02","D03","D04","D05","D06","D07","D08","D09","D10","D11","D12","E01","E02","E03","E04","E05","E06","E07","E08","E09","E10","E11","E12","F01","F02","F03","F04","F05","F06","F07","F08","F09","F10","F11","F12","G01","G02","G03","G04","G05","G06","G07","G08","G09","G10","G11","G12","H01","H02","H03","H04","H05","H06","H07","H08","H09","H10","H11","H12")
  platemap <- data.frame(well=wells)
  platemap$row <- substr(platemap$well, 1, 1)
  platemap$column <- substr(platemap$well, 2, 3)
  return(platemap)
}
empty_384_map <- function(){
  wells <-c("A01","A02","A03","A04","A05","A06","A07","A08","A09","A10","A11","A12","A13","A14","A15","A16","A17","A18","A19","A20","A21","A22","A23","A24","B01","B02","B03","B04","B05","B06","B07","B08","B09","B10","B11","B12","B13","B14","B15","B16","B17","B18","B19","B20","B21","B22","B23","B24","C01","C02","C03","C04","C05","C06","C07","C08","C09","C10","C11","C12","C13","C14","C15","C16","C17","C18","C19","C20","C21","C22","C23","C24","D01","D02","D03","D04","D05","D06","D07","D08","D09","D10","D11","D12","D13","D14","D15","D16","D17","D18","D19","D20","D21","D22","D23","D24","E01","E02","E03","E04","E05","E06","E07","E08","E09","E10","E11","E12","E13","E14","E15","E16","E17","E18","E19","E20","E21","E22","E23","E24","F01","F02","F03","F04","F05","F06","F07","F08","F09","F10","F11","F12","F13","F14","F15","F16","F17","F18","F19","F20","F21","F22","F23","F24","G01","G02","G03","G04","G05","G06","G07","G08","G09","G10","G11","G12","G13","G14","G15","G16","G17","G18","G19","G20","G21","G22","G23","G24","H01","H02","H03","H04","H05","H06","H07","H08","H09","H10","H11","H12","H13","H14","H15","H16","H17","H18","H19","H20","H21","H22","H23","H24","I01","I02","I03","I04","I05","I06","I07","I08","I09","I10","I11","I12","I13","I14","I15","I16","I17","I18","I19","I20","I21","I22","I23","I24","J01","J02","J03","J04","J05","J06","J07","J08","J09","J10","J11","J12","J13","J14","J15","J16","J17","J18","J19","J20","J21","J22","J23","J24","K01","K02","K03","K04","K05","K06","K07","K08","K09","K10","K11","K12","K13","K14","K15","K16","K17","K18","K19","K20","K21","K22","K23","K24","L01","L02","L03","L04","L05","L06","L07","L08","L09","L10","L11","L12","L13","L14","L15","L16","L17","L18","L19","L20","L21","L22","L23","L24","M01","M02","M03","M04","M05","M06","M07","M08","M09","M10","M11","M12","M13","M14","M15","M16","M17","M18","M19","M20","M21","M22","M23","M24","N01","N02","N03","N04","N05","N06","N07","N08","N09","N10","N11","N12","N13","N14","N15","N16","N17","N18","N19","N20","N21","N22","N23","N24","O01","O02","O03","O04","O05","O06","O07","O08","O09","O10","O11","O12","O13","O14","O15","O16","O17","O18","O19","O20","O21","O22","O23","O24","P01","P02","P03","P04","P05","P06","P07","P08","P09","P10","P11","P12","P13","P14","P15","P16","P17","P18","P19","P20","P21","P22","P23","P24")
  platemap <- data.frame(well=wells)
  platemap$row <- substr(platemap$well, 1, 1)
  platemap$column <- substr(platemap$well, 2, 3)
  return(platemap)
}

```


```{r bay1, echo=FALSE, fig.show="hold", out.width="50%"}
  bay_inc <- subset(inc, QpcrInstrument==1)
  map <- empty_plate_map()
  if(nrow(bay_inc) != 0){
    incWells <- as.data.frame(table(bay_inc$ParentPlateWell))
    map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 1 inconclusives")
  }
  
    bay_pos <- subset(pos, QpcrInstrument==1)
  map <- empty_plate_map()
  if(nrow(bay_pos) != 0){
    posWells <- as.data.frame(table(bay_pos$ParentPlateWell))
    map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 1 positives")
    
      bay_inc <- subset(inc, QpcrInstrument==1)
      

}

```

```{r 384bay1, echo=FALSE, fig.show="hold", out.width="50%"}
bay_inc <- subset(inc, QpcrInstrument==1)
map <- empty_384_map()
if(nrow(bay_inc) != 0){
  incWells <- as.data.frame(table(bay_inc$CompressionPlateWell))
  map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 1 inconclusives")
}

bay_pos <- subset(pos, QpcrInstrument==1)
map <- empty_384_map()
if(nrow(bay_pos) != 0){
  posWells <- as.data.frame(table(bay_pos$CompressionPlateWell))
  map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 1 positives")
  
  bay_inc <- subset(inc, QpcrInstrument==1)
  
  
}

```

```{r bay2, echo=FALSE, fig.show="hold", out.width="50%"}
  bay_inc <- subset(inc, QpcrInstrument==2)
  map <- empty_plate_map()
  if(nrow(bay_inc) != 0){
    incWells <- as.data.frame(table(bay_inc$ParentPlateWell))
    map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 2 inconclusives")
  }
  
    bay_pos <- subset(pos, QpcrInstrument==2)
  map <- empty_plate_map()
  if(nrow(bay_pos) != 0){
    posWells <- as.data.frame(table(bay_pos$ParentPlateWell))
    map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 2 positives")
}

```

```{r 384bay2, echo=FALSE, fig.show="hold", out.width="50%"}
bay_inc <- subset(inc, QpcrInstrument==2)
map <- empty_384_map()
if(nrow(bay_inc) != 0){
  incWells <- as.data.frame(table(bay_inc$CompressionPlateWell))
  map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 2 inconclusives")
}

bay_pos <- subset(pos, QpcrInstrument==2)
map <- empty_384_map()
if(nrow(bay_pos) != 0){
  posWells <- as.data.frame(table(bay_pos$CompressionPlateWell))
  map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 2 positives")
}

```

```{r bay3, echo=FALSE, fig.show="hold", out.width="50%"}
  bay_inc <- subset(inc, QpcrInstrument==3)
  map <- empty_plate_map()
  if(nrow(bay_inc) != 0){
    incWells <- as.data.frame(table(bay_inc$ParentPlateWell))
    map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 3 inconclusives")
  }
  
    bay_pos <- subset(pos, QpcrInstrument==3)
  map <- empty_plate_map()
  if(nrow(bay_pos) != 0){
    posWells <- as.data.frame(table(bay_pos$ParentPlateWell))
    map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 3 positives")
}

```

```{r 384bay3, echo=FALSE, fig.show="hold", out.width="50%"}
bay_inc <- subset(inc, QpcrInstrument==3)
map <- empty_384_map()
if(nrow(bay_inc) != 0){
  incWells <- as.data.frame(table(bay_inc$CompressionPlateWell))
  map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 3 inconclusives")
}

bay_pos <- subset(pos, QpcrInstrument==3)
map <- empty_384_map()
if(nrow(bay_pos) != 0){
  posWells <- as.data.frame(table(bay_pos$CompressionPlateWell))
  map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 3 positives")
}

```

```{r bay4, echo=FALSE, fig.show="hold", out.width="50%"}
  bay_inc <- subset(inc, QpcrInstrument==4)
  map <- empty_plate_map()
  if(nrow(bay_inc) != 0){
    incWells <- as.data.frame(table(bay_inc$ParentPlateWell))
    map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 4 inconclusives")
  }
  
    bay_pos <- subset(pos, QpcrInstrument==4)
  map <- empty_plate_map()
  if(nrow(bay_pos) != 0){
    posWells <- as.data.frame(table(bay_pos$ParentPlateWell))
    map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 4 positives")
}

```

```{r 384bay4, echo=FALSE, fig.show="hold", out.width="50%"}
bay_inc <- subset(inc, QpcrInstrument==4)
map <- empty_384_map()
if(nrow(bay_inc) != 0){
  incWells <- as.data.frame(table(bay_inc$CompressionPlateWell))
  map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 4 inconclusives")
}

bay_pos <- subset(pos, QpcrInstrument==4)
map <- empty_384_map()
if(nrow(bay_pos) != 0){
  posWells <- as.data.frame(table(bay_pos$CompressionPlateWell))
  map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 4 positives")
}

```

```{r bay5, echo=FALSE, fig.show="hold", out.width="50%"}
  bay_inc <- subset(inc, QpcrInstrument==5)
  map <- empty_plate_map()
  if(nrow(bay_inc) != 0){
    incWells <- as.data.frame(table(bay_inc$ParentPlateWell))
    map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 5 inconclusives")
  }
  
    bay_pos <- subset(pos, QpcrInstrument==5)
  map <- empty_plate_map()
  if(nrow(bay_pos) != 0){
    posWells <- as.data.frame(table(bay_pos$ParentPlateWell))
    map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 5 positives")
}

```

```{r 384bay5, echo=FALSE, fig.show="hold", out.width="50%"}
bay_inc <- subset(inc, QpcrInstrument==5)
map <- empty_384_map()
if(nrow(bay_inc) != 0){
  incWells <- as.data.frame(table(bay_inc$CompressionPlateWell))
  map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 5 inconclusives")
}

bay_pos <- subset(pos, QpcrInstrument==5)
map <- empty_384_map()
if(nrow(bay_pos) != 0){
  posWells <- as.data.frame(table(bay_pos$CompressionPlateWell))
  map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 5 positives")
}

```

```{r bay6, echo=FALSE, fig.show="hold", out.width="50%"}
  bay_inc <- subset(inc, QpcrInstrument==6)
  map <- empty_plate_map()
  if(nrow(bay_inc) != 0){
    incWells <- as.data.frame(table(bay_inc$ParentPlateWell))
    map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 6 inconclusives")
  }
  
    bay_pos <- subset(pos, QpcrInstrument==6)
  map <- empty_plate_map()
  if(nrow(bay_pos) != 0){
    posWells <- as.data.frame(table(bay_pos$ParentPlateWell))
    map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 6 positives")
}

```

```{r 384bay6, echo=FALSE, fig.show="hold", out.width="50%"}
bay_inc <- subset(inc, QpcrInstrument==6)
map <- empty_384_map()
if(nrow(bay_inc) != 0){
  incWells <- as.data.frame(table(bay_inc$CompressionPlateWell))
  map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 6 inconclusives")
}

bay_pos <- subset(pos, QpcrInstrument==6)
map <- empty_384_map()
if(nrow(bay_pos) != 0){
  posWells <- as.data.frame(table(bay_pos$CompressionPlateWell))
  map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 6 positives")
}

```

```{r bay7, echo=FALSE, fig.show="hold", out.width="50%"}
  bay_inc <- subset(inc, QpcrInstrument==7)
  map <- empty_plate_map()
  if(nrow(bay_inc) != 0){
    incWells <- as.data.frame(table(bay_inc$ParentPlateWell))
    map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 7 inconclusives")
  }
  
    bay_pos <- subset(pos, QpcrInstrument==7)
  map <- empty_plate_map()
  if(nrow(bay_pos) != 0){
    posWells <- as.data.frame(table(bay_pos$ParentPlateWell))
    map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 7 positives")
}

```

```{r 384bay7, echo=FALSE, fig.show="hold", out.width="50%"}
bay_inc <- subset(inc, QpcrInstrument==7)
map <- empty_384_map()
if(nrow(bay_inc) != 0){
  incWells <- as.data.frame(table(bay_inc$CompressionPlateWell))
  map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 7 inconclusives")
}

bay_pos <- subset(pos, QpcrInstrument==7)
map <- empty_384_map()
if(nrow(bay_pos) != 0){
  posWells <- as.data.frame(table(bay_pos$CompressionPlateWell))
  map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 7 positives")
}

```

```{r bay8, echo=FALSE, fig.show="hold", out.width="50%"}
  bay_inc <- subset(inc, QpcrInstrument==8)
  map <- empty_plate_map()
  if(nrow(bay_inc) != 0){
    incWells <- as.data.frame(table(bay_inc$ParentPlateWell))
    map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 8 inconclusives")
  }
  
    bay_pos <- subset(pos, QpcrInstrument==8)
  map <- empty_plate_map()
  if(nrow(bay_pos) != 0){
    posWells <- as.data.frame(table(bay_pos$ParentPlateWell))
    map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 8 positives")
}

```

```{r 384bay8, echo=FALSE, fig.show="hold", out.width="50%"}
bay_inc <- subset(inc, QpcrInstrument==8)
map <- empty_384_map()
if(nrow(bay_inc) != 0){
  incWells <- as.data.frame(table(bay_inc$CompressionPlateWell))
  map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 8 inconclusives")
}

bay_pos <- subset(pos, QpcrInstrument==8)
map <- empty_384_map()
if(nrow(bay_pos) != 0){
  posWells <- as.data.frame(table(bay_pos$CompressionPlateWell))
  map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 8 positives")
}

```

```{r bay9, echo=FALSE, fig.show="hold", out.width="50%"}
  bay_inc <- subset(inc, QpcrInstrument==9)
  map <- empty_plate_map()
  if(nrow(bay_inc) != 0){
    incWells <- as.data.frame(table(bay_inc$ParentPlateWell))
    map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 9 inconclusives")
  }
  
    bay_pos <- subset(pos, QpcrInstrument==9)
  map <- empty_plate_map()
  if(nrow(bay_pos) != 0){
    posWells <- as.data.frame(table(bay_pos$ParentPlateWell))
    map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 9 positives")
}

```

```{r 384bay9, echo=FALSE, fig.show="hold", out.width="50%"}
bay_inc <- subset(inc, QpcrInstrument==9)
map <- empty_384_map()
if(nrow(bay_inc) != 0){
  incWells <- as.data.frame(table(bay_inc$CompressionPlateWell))
  map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 9 inconclusives")
}

bay_pos <- subset(pos, QpcrInstrument==9)
map <- empty_384_map()
if(nrow(bay_pos) != 0){
  posWells <- as.data.frame(table(bay_pos$CompressionPlateWell))
  map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 9 positives")
}

```

```{r bay10, echo=FALSE, fig.show="hold", out.width="50%"}
  bay_inc <- subset(inc, QpcrInstrument==10)
  map <- empty_plate_map()
  if(nrow(bay_inc) != 0){
    incWells <- as.data.frame(table(bay_inc$ParentPlateWell))
    map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 10 inconclusives")
  }
  
    bay_pos <- subset(pos, QpcrInstrument==10)
  map <- empty_plate_map()
  if(nrow(bay_pos) != 0){
    posWells <- as.data.frame(table(bay_pos$ParentPlateWell))
    map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 10 positives")
}

```

```{r 384bay10, echo=FALSE, fig.show="hold", out.width="50%"}
bay_inc <- subset(inc, QpcrInstrument==10)
map <- empty_384_map()
if(nrow(bay_inc) != 0){
  incWells <- as.data.frame(table(bay_inc$CompressionPlateWell))
  map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 10 inconclusives")
}

bay_pos <- subset(pos, QpcrInstrument==10)
map <- empty_384_map()
if(nrow(bay_pos) != 0){
  posWells <- as.data.frame(table(bay_pos$CompressionPlateWell))
  map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 10 positives")
}

```

```{r bay11, echo=FALSE, fig.show="hold", out.width="50%"}
  bay_inc <- subset(inc, QpcrInstrument==11)
  map <- empty_plate_map()
  if(nrow(bay_inc) != 0){
    incWells <- as.data.frame(table(bay_inc$ParentPlateWell))
    map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 11 inconclusives")
  }
  
    bay_pos <- subset(pos, QpcrInstrument==11)
  map <- empty_plate_map()
  if(nrow(bay_pos) != 0){
    posWells <- as.data.frame(table(bay_pos$ParentPlateWell))
    map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 11 positives")
}

```

```{r 384bay11, echo=FALSE, fig.show="hold", out.width="50%"}
bay_inc <- subset(inc, QpcrInstrument==11)
map <- empty_384_map()
if(nrow(bay_inc) != 0){
  incWells <- as.data.frame(table(bay_inc$CompressionPlateWell))
  map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 11 inconclusives")
}

bay_pos <- subset(pos, QpcrInstrument==11)
map <- empty_384_map()
if(nrow(bay_pos) != 0){
  posWells <- as.data.frame(table(bay_pos$CompressionPlateWell))
  map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 11 positives")
}

```

```{r bay12, echo=FALSE, fig.show="hold", out.width="50%"}
  bay_inc <- subset(inc, QpcrInstrument==12)
  map <- empty_plate_map()
  if(nrow(bay_inc) != 0){
    incWells <- as.data.frame(table(bay_inc$ParentPlateWell))
    map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 12 inconclusives")
  }
  
    bay_pos <- subset(pos, QpcrInstrument==12)
  map <- empty_plate_map()
  if(nrow(bay_pos) != 0){
    posWells <- as.data.frame(table(bay_pos$ParentPlateWell))
    map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 12 positives")
}

```

```{r 384bay12, echo=FALSE, fig.show="hold", out.width="50%"}
bay_inc <- subset(inc, QpcrInstrument==12)
map <- empty_384_map()
if(nrow(bay_inc) != 0){
  incWells <- as.data.frame(table(bay_inc$CompressionPlateWell))
  map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 12 inconclusives")
}

bay_pos <- subset(pos, QpcrInstrument==12)
map <- empty_384_map()
if(nrow(bay_pos) != 0){
  posWells <- as.data.frame(table(bay_pos$CompressionPlateWell))
  map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 12 positives")
}

```

```{r bay13, echo=FALSE, fig.show="hold", out.width="50%"}
  bay_inc <- subset(inc, QpcrInstrument==13)
  map <- empty_plate_map()
  if(nrow(bay_inc) != 0){
    incWells <- as.data.frame(table(bay_inc$ParentPlateWell))
    map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 13 inconclusives")
  }
  
    bay_pos <- subset(pos, QpcrInstrument==13)
  map <- empty_plate_map()
  if(nrow(bay_pos) != 0){
    posWells <- as.data.frame(table(bay_pos$ParentPlateWell))
    map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
    ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
      geom_tile(colour="black")+
      scale_y_discrete(limits=rev) +
      scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
      geom_text(aes(label=Freq))+
      labs(title="Bay 13 positives")
}

```

```{r 384bay13, echo=FALSE, fig.show="hold", out.width="50%"}
bay_inc <- subset(inc, QpcrInstrument==13)
map <- empty_384_map()
if(nrow(bay_inc) != 0){
  incWells <- as.data.frame(table(bay_inc$CompressionPlateWell))
  map <- merge(map, incWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 13 inconclusives")
}

bay_pos <- subset(pos, QpcrInstrument==13)
map <- empty_384_map()
if(nrow(bay_pos) != 0){
  posWells <- as.data.frame(table(bay_pos$CompressionPlateWell))
  map <- merge(map, posWells, by.x = "well", by.y= "Var1", all.x=T)
  ggplot(data=map, mapping=aes(x=column,y=row,fill=Freq)) +
    geom_tile(colour="black")+
    scale_y_discrete(limits=rev) +
    scale_fill_gradient(limits= c(0,NA), name="Frequency", low="white", high="red", guide = FALSE)+
    geom_text(aes(label=Freq))+
    labs(title="Bay 13 positives")
}

```

